// Tournament
const SET_TOURNAMENTS_DATA = '@TOURNAMENT.SET_TOURNAMENTS_DATA'
const ADD_TOURNAMENT_DATA = '@TOURNAMENT.ADD_TOURNAMENT_DATA'

// Player
const SET_PLAYERS_DATA = '@PLAYER.GET_PLAYER_DATA'
const ADD_PLAYER = '@PLAYER.ADD_PLAYER'

// Venue
const SET_VENUES_DATA = '@VENUE.SET_VENUES_DATA'
const ADD_VENUE = '@VENUE.ADD_VENUE'

// Venue
const SET_MATCHES_DATA = '@MATCH.SET_MATcHES_DATA'
const ADD_MATCH = '@MATCH.ADD_MATCH'
const CLEAR_MATCHES_DATA = '@MATCH.CLEAR_MATCHES_DATA'


export { SET_TOURNAMENTS_DATA, ADD_TOURNAMENT_DATA, SET_PLAYERS_DATA, ADD_PLAYER, 
        SET_VENUES_DATA, ADD_VENUE, SET_MATCHES_DATA, ADD_MATCH, CLEAR_MATCHES_DATA }
