// Tournament
const SET_TOURNAMENTS_DATA = '@TOURNAMENT.SET_TOURNAMENTS_DATA'
const ADD_TOURNAMENT_DATA = '@TOURNAMENT.ADD_TOURNAMENT_DATA'

// Player
const SET_PLAYERS_DATA = '@PLAYER.GET_PLAYER_DATA'
const ADD_PLAYER = '@PLAYER.ADD_PLAYER'

// Venue
const SET_VENUES_DATA = '@VENUE.SET_VENUES_DATA'
const ADD_VENUE = '@VENUE.ADD_VENUE'

export { SET_TOURNAMENTS_DATA, ADD_TOURNAMENT_DATA, SET_PLAYERS_DATA, ADD_PLAYER, SET_VENUES_DATA, ADD_VENUE }
